version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: terraform
    # Only directories support globbing.
    # https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#directories-or-directory--
    directories:
      - /infrastructure/**/terraform/
    schedule:
      interval: daily
    groups:
      scaleway:
        patterns:
          - scaleway/scaleway
      github:
        patterns:
          - integrations/github
